### ISSUE TITLE
Compiler information

### ISSUE THREAD

**Issue by joshvoll** [thesephist/ink#7]
This is a really good lang, i would like to know where i can see the internals of the compiler, of course i'm new developer, but i see the code but i don't see the compiler

**Comment by thesephist** [comment]
Hey @joshvoll, Ink currently doesn't have a compiler that compiles to native machine code. It has:

1. An interpreter, which is written in Go and in this repository. You can start with the CLI file [here](https://github.com/thesephist/ink/blob/master/cmd/ink.go) if you want to check out the interpreter's source code. You can also download and use it according to [instructions on this guide](https://dotink.co/docs/overview/#quick-start).
2. A compiler that compiles Ink to JavaScript, which is in [this repo](https://github.com/thesephist/september). It's written in Ink itself and self-hosts (compiles itself). But it obviously doesn't produce a native executable, it produces a JavaScript bundle. The internals of this compiler are documented in [this blog post](https://dotink.co/posts/september/) too.

Does that help you find what you were looking for?
