### ISSUE TITLE
Docs - Functions, closures, and recursion

### ISSUE THREAD

**Issue by Sophismata** [thesephist/ink#8]
Was reading the docs, and in the Overview's [Functions, closures, and recursion](https://dotink.co/docs/overview/#functions-closures-and-recursion) topic, the example Fibonacci recursive function is as follows:

> A tail call optimized implementation wraps loop variables into the arguments.
> ```
> fibRec := (n, a, b) => n :: {
>     0 -> a
>     _ -> fibRec(b, a + b, n - 1)
> }
> 
> fib := n => fibRec(n, 0, 1)
> ```

Should the function definition not instead be:
```
fibRec := (n, a, b) => n :: {
    0 -> a
    _ -> fibRec(n - 1, a + b, a)
}
```

Sorry if I'm missing something obvious.

**Comment by thesephist** [comment]
Good catch! Thanks for filing an issue. I must not have tested my sample code properly. You're close, but it should be

```
fibRec := (n, a, b) => n :: {
    0 -> a
    _ -> fibRec(n - 1, b, a + b)
}

fib := n => fibRec(n, 0, 1)
```

Just fixed in [`7bc6ef`](https://github.com/thesephist/dotink/commit/7bc6efb8383f53a267c6fa2d68d3af4ef42fea64) and should be going live soon :)

**Comment by Sophismata** [comment]
Cheers 🙂

I spent a while trying to make the original function make sense before guessing it might be a mistake.
